### ISSUE TITLE
Why get_nodes method takes ownership over service name?

### ISSUE THREAD

**Issue by SkeLLLa** [stusmall/consul-rust#13]
Hello. The question is about method
https://github.com/stusmall/consul-rust/blob/9c724a5fea89d3457deaa9a2c5d33bcdcd6f26c0/src/catalog.rs#L40

Why it's taking ownership over service name param instead of just borrowing it?

**Comment by stusmall** [comment]
It should just borrow it.  I'm currently working on completely reworking the whole library.  There are multiple issues with it.  Check this branch: https://github.com/stusmall/consul-rust/tree/refactor

If the features you need are supported the code is in much better shape.

**Comment by stusmall** [comment]
This has since been fixed
