### ISSUE TITLE
I'd like to maintain this project.

### ISSUE THREAD

**Issue by stusmall** [stusmall/consul-rust#3]
First I wanted to say thanks for writing this great project.  I'm finding it very useful.

Since this project is currently deprecated and no longer maintained I'd like to offer to take over maintenance of it.  There are a couple things I would need to be able to do this effectively.  First if you could transfer control of the github project to me. Documentation on how to do this and what it entails can be found here: https://help.github.com/articles/about-repository-transfers/

Next I would also need to be added as an owner on crates.io.  Instructions for that can be found here:
http://doc.crates.io/crates-io.html#cargo-owner

Once again thanks for the hard work on the project and I hope you let me let it live on.

Thanks!

**Comment by youngking** [comment]
Thanks for taking over this project, I'd done the above instructions.

**Comment by stusmall** [comment]
Thank you so much.  One last question,  would you have any objections to be re-licensing it to dual licensed MIT/Apache instead of MIT?

**Comment by youngking** [comment]
No problem, just do it.

**Comment by stusmall** [comment]
Thank you!
